version: '3'

services:
  rabbit:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
      - RABBITMQ_DEFAULT_VHOST=test
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
      - "15672"

